#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: 飞书自建应用开通（仅人工步骤），供 T11 扫码登录使用
# 开发者后台的导航名称可能随飞书版本微调；各阶段附文档入口供对照。
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=7

banner "飞书扫码登录配置（kanban）"

# ── Stage 1: 登录飞书开放平台 ────────────────────────────────────────────
stage "登录飞书开放平台"
say "本向导帮你开通「企业自建应用」并把扫码登录凭据写进 .env。"
say "所有步骤都在飞书开放平台完成，只能由人操作（扫码、管理员审批）。"
open_url "https://open.feishu.cn/"
step "用飞书 App 扫码登录开放平台（个人或企业账号均可创建自建应用）。"
note "文档入口：https://open.feishu.cn/document/ （如需帮助可搜「企业自建应用」）"
pause "登录完成后按 Enter 继续"

# ── Stage 2: 创建企业自建应用 ────────────────────────────────────────────
stage "创建企业自建应用"
open_url "https://open.feishu.cn/app"
step "进入「开发者后台」，点击「创建企业自建应用」。"
step "填写应用名称（如：Agent 任务看板）与描述，上传任意图标，创建。"
step "创建后进入应用详情页，后续阶段都在这里操作。"
pause "应用创建完成后按 Enter 继续"

# ── Stage 3: 获取应用凭证（App ID / App Secret）─────────────────────────
stage "获取应用凭证"
say "在应用详情页左侧找到「凭证与基础信息」（部分版本叫「凭证与基础信息」）。"
open_url "https://open.feishu.cn/app"
step "进入「凭证与基础信息」页面，复制 App ID（cli_ 开头）。"
ask FEISHU_APP_ID "粘贴 App ID："
step "点击 App Secret 的「查看/复制」，复制密钥。"
ask_secret FEISHU_APP_SECRET "粘贴 App Secret（输入隐藏）："
write_env FEISHU_APP_ID "$FEISHU_APP_ID"
write_env FEISHU_APP_SECRET "$FEISHU_APP_SECRET"
pause "两项都写入 .env 后按 Enter 继续"

# ── Stage 4: 开通网页应用能力 + 配置重定向 URL ───────────────────────────
stage "配置网页应用与重定向 URL"
say "扫码登录依赖「网页应用」能力与安全设置里的重定向 URL。"
open_url "https://open.feishu.cn/app"
step "左侧「添加应用能力」（或「应用能力」）→ 选择「网页应用」开通。"
step "网页应用的「桌面端首页」填本地登录页：http://localhost:3000/login"
step "左侧「安全设置」→「重定向 URL」→ 新增一条（默认回调地址如下）。"
note "默认回调：http://localhost:3000/api/auth/feishu/callback"
note "部署到公网时，请把回调与首页都换成真实域名后重跑本向导更新。"
ask FEISHU_REDIRECT_URI "回调地址（Enter 用默认）："
[[ -z "$FEISHU_REDIRECT_URI" ]] && FEISHU_REDIRECT_URI="http://localhost:3000/api/auth/feishu/callback"
write_env FEISHU_REDIRECT_URI "$FEISHU_REDIRECT_URI"
pause "能力开通、两处 URL 配好后按 Enter 继续"

# ── Stage 5: 开通用户信息权限 ────────────────────────────────────────────
stage "开通用户信息权限"
say "扫码后需要读取用户基本信息（姓名、union_id）来创建成员。"
open_url "https://open.feishu.cn/app"
step "左侧「权限管理」→ 搜索并开通「获取用户基本信息」"
step "如列表里也有「获取用户 userID / union_id」类权限，一并开通。"
note "权限名可能随版本调整：目标是能读 name 与 union_id/open_id。"
pause "权限开通完成后按 Enter 继续"

# ── Stage 6: 发布应用 ────────────────────────────────────────────────────
stage "发布应用版本"
say "未发布的应用对本企业成员不可用，扫码登录会被拒绝。"
open_url "https://open.feishu.cn/app"
step "左侧「版本管理与发布」→「创建版本」→ 填版本号与更新说明。"
step "可用范围选「全体成员」（或按需指定），提交发布。"
step "企业管理员会收到审批通知；自己有管理员权限时可直接通过。"
pause "版本发布通过后按 Enter 继续"

# ── Stage 7: 本地验证 ────────────────────────────────────────────────────
stage "本地验证扫码登录"
say "凭据已就绪，起本地环境做一次真实扫码验证。"
step "终端运行：docker compose up --build（或 npm run dev，需先起 MySQL）。"
step "浏览器打开 http://localhost:3000/login ，点击「飞书扫码登录」。"
step "用飞书 App 扫码并授权，应跳转到看板并显示你的名字。"
note "首个扫码者自动成为组织管理员。"
if confirm "扫码登录成功了吗？"; then
  note "很好，T11 全部完成。"
else
  warn "排查：.env 三项是否正确、重定向 URL 是否一致、应用是否已发布、权限是否生效。"
  note "可重跑 npm run feishu:setup 修正任意一步。"
fi
# ──────────────────────────────────────────────────────────────────────────

finish
